version: '3.9'
services:
  db:
    image: 'mariadb:latest'
    volumes:
      - './db/mysql:/var/lib/mysql'
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
  wp:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./backend/wordpress:/var/www/html"
      - "./backend/plugins:/var/www/html/wp-content/plugins"