version: '3.9'
services:
  db:
    container_name: db
    build:
      dockerfile: DockerfileDB
      context: ./db
    image: 'mariadb:latest'
    volumes:
      - './db/mysql:/var/lib/mysql'
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD: example
      - MARIADB_DATABASE: wordpress_db
      - MARIADB_USER: user
      - MARIADB_PASSWORD: password

  wp:
    container_name: backend
    build:
      dockerfile: DockerfileWP
      context: ./backend
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - "./backend/wordpress:/var/www/html"
      - "./backend/plugins:/var/www/html/wp-content/plugins"
    environment:
      - WORDPRESS_DB_HOST: db:3306
      - WORDPRESS_DB_USER: user
      - WORDPRESS_DB_PASSWORD: password
      - WORDPRESS_DB_NAME: wordpress_db

  frontend:
    container_name: frontend
    command: bash -c 'npm i && npm start'
    expose:
        - '3000'
    image: node
    ports:
        - '3000:3000'
    user: node
    volumes:
        - ./frontend:/frontend
    working_dir: /frontend