version: '3.9'
services:
  db:
    container_name: db
    build:
      dockerfile: DockerfileDB
      context: ./db
    image: 'mariadb:latest'
    volumes:
      - './db/mysql:/var/lib/mysql'
    ports:
      - 3306:3306

  wp:
    container_name: backend
    build:
      dockerfile: DockerfileWP
      context: ./backend
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - "./backend/wordpress:/var/www/html"
      - "./backend/plugins:/var/www/html/wp-content/plugins"

  frontend:
    container_name: frontend
    build:
      dockerfile: DockerfileFE
      context: ./frontend
    expose:
        - '3000'
    image: node
    ports:
        - '3000:3000'
    user: node
    volumes:
        - ./frontend:/frontend
    working_dir: /frontend