version: '3.9'
services:
  db:
    container_name: db
    build:
      dockerfile: DockerfileDB
      context: ./db
    image: 'mariadb:latest'
    volumes:
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - 3306:3306
    networks:
      - wp
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}

  wp:
    container_name: backend
    build:
      dockerfile: DockerfileWP
      context: ./backend
    command: bash -c 'install_wordpress && apache2-foreground'
    ports:
      - 80:80
    networks:
      - wp
    depends_on:
      - db
    volumes:
      - "./backend/wordpress:/var/www/html"
      - "./backend/install_wordpress.sh:/usr/local/bin/install_wordpress"
      - "./backend/plugins:/var/www/html/wp-content/plugins"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  frontend:
    container_name: frontend
    command: bash -c 'npm i && npm run dev'
    expose:
      - '3000'
    image: node
    ports:
      - '3000:3000'
    networks:
      - wp
    volumes:
        - ./frontend:/frontend
    working_dir: /frontend
    
networks:
    wp:
      driver: bridge